### ISSUE TITLE
Svelte 3 Support

### ISSUE THREAD

**Issue by jascodes** [ArdenIvanov/svelte-intellisense#11]

**Comment by imperez** [comment]
@ArdenIvanov just curious if there was a plan for any v3 support? Seems like the extension don't work at all in it.

**Comment by ArdenIvanov** [comment]
Yes, you can see it as a first item in TODO list :) working on v3 support now since it is finally released

**Comment by jascodes** [comment]
@ArdenIvanov Your work is very much appreciated man.
Cheers :beers:

**Comment by imperez** [comment]
D'oh I missed the TODO list! Great to hear it's being worked on and yes I agree with @jascodes your work is incredibly appreciated!

**Comment by arxpoetica** [comment]
@ArdenIvanov anything we can do to help move this along? Is there a v3 branch? I'm missing a lot of these features boo hoo...

**Comment by ArdenIvanov** [comment]
@arxpoetica yes, there is a v3_support branch, but it is almost ready by itself. This extension is dependent on sveltedoc-parser package, I believe you can help to finish v3 support there - take a look at https://github.com/alexprey/sveltedoc-parser/projects/1

**Comment by ArdenIvanov** [comment]
Implemented partially in 0.6.0, leftovers will be created and closed as a separate issues
