### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by stevesob** [ArdenIvanov/svelte-intellisense#16]
All of a sudden I am constantly getting this error message continuously in my Output Window.

[Error - 10:43:18 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'data' of undefined
  Code: -32603 

I'm not sure how to fix or where it is coming from.

**Comment by ArdenIvanov** [comment]
Same as #14
