### ISSUE TITLE
V3

### ISSUE THREAD

**Issue by minkir014** [ArdenIvanov/svelte-intellisense#18]
When is it intended to support svelte 3? I want to know Is it that hard to add svelte 3 support?

**Comment by alexprey** [comment]
For 0.6 version we already add partial support of svelte v3. And we still continue work under new version with supporting of more features of v3

**Comment by minkir014** [comment]
I mean that the support of V3 must be equal to V2.

**Comment by ArdenIvanov** [comment]
Version 0.7.0 adds equal support. If some particular feature for v3 is missing, please raise a separate issue for that.

**Comment by minkir014** [comment]
You mean that now Svelte 3 has equal support to Svelte 2.

**Comment by ArdenIvanov** [comment]
Yes, I do. There are some v2 specific features that had been deprecated in v3, like set/get for component data. And there are v3 only features which are not yet supported by the plugin.
